name: animated_snack_bar
description: Easily show beautiful snack bars directly using overlays. Create custom snack bars and show them with awesome animations.
version: 0.3.1
homepage: https://github.com/JulyWitch
repository: https://github.com/JulyWitch/animated_snack_bar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/regular/
    - assets/monochrome/